name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # má»—i khi push vÃ o master sáº½ cháº¡y

permissions:
  contents: write  # cáº§n quyá»n Ä‘á»ƒ ghi vÃ o nhÃ¡nh gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¹ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # hoáº·c version báº¡n Ä‘ang dÃ¹ng

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ—ï¸ Build Angular app
        run: npm run build -- --configuration production

      - name: ğŸš€ Deploy to GitHub Pages
        uses: minhluongutc
        with:
          branch: master  # branch sáº½ Ä‘Æ°á»£c dÃ¹ng Ä‘á»ƒ host GitHub Pages
          folder: dist/loveluna  # Ä‘Æ°á»ng dáº«n thÆ° má»¥c build (sá»­a láº¡i cho Ä‘Ãºng)
